id = "neocode"
name = "NeoCode"
description = "The open source coding agent."
version = "1.1.49"
schema_version = 1
authors = ["KhulnaSoft"]
repository = "https://github.com/neopilot-ai/neocode"

[agent_servers.neocode]
name = "NeoCode"
icon = "./icons/neocode.svg"

[agent_servers.neocode.targets.darwin-aarch64]
archive = "https://github.com/neopilot-ai/neocode/releases/download/v1.1.1/neocode-darwin-arm64.zip"
cmd = "./neocode"
args = ["acp"]

[agent_servers.neocode.targets.darwin-x86_64]
archive = "https://github.com/neopilot-ai/neocode/releases/download/v1.1.1/neocode-darwin-x64.zip"
cmd = "./neocode"
args = ["acp"]

[agent_servers.neocode.targets.linux-aarch64]
archive = "https://github.com/neopilot-ai/neocode/releases/download/v1.1.1/neocode-linux-arm64.tar.gz"
cmd = "./neocode"
args = ["acp"]

[agent_servers.neocode.targets.linux-x86_64]
archive = "https://github.com/neopilot-ai/neocode/releases/download/v1.1.1/neocode-linux-x64.tar.gz"
cmd = "./neocode"
args = ["acp"]

[agent_servers.neocode.targets.windows-x86_64]
archive = "https://github.com/neopilot-ai/neocode/releases/download/v1.1.1/neocode-windows-x64.zip"
cmd = "./neocode.exe"
args = ["acp"]
