name = "neocode-web"
main = "./dist/_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "neocode-web-prod"
routes = [
  { pattern = "neo.khulnasoft.com/docs/*", zone_name = "khulnasoft.com" }
]

[env.dev]
name = "neocode-web-dev"
routes = [
  { pattern = "dev.neo.khulnasoft.com/docs/*", zone_name = "khulnasoft.com" }
]

[env.staging]
name = "neocode-web-staging"
routes = [
  { pattern = "staging.neo.khulnasoft.com/docs/*", zone_name = "khulnasoft.com" }
]

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "d20ff02478d64d99848e7100af98f52f"

[[env.dev.kv_namespaces]]
binding = "CACHE"
id = "d20ff02478d64d99848e7100af98f52f"
