#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Running eslint"
if [ -f "../../node_modules/.bin/eslint" ]; then
  ../../node_modules/.bin/eslint .
elif command -v eslint >/dev/null 2>&1; then
  eslint .
else
  echo "ESLint not found, skipping..."
fi

echo "==> Building"
./scripts/build

echo "==> Checking types"
if [ -f "./node_modules/typescript/bin/tsc" ]; then
  ./node_modules/typescript/bin/tsc
elif command -v tsc >/dev/null 2>&1; then
  tsc --noEmit
else
  echo "TypeScript compiler not found, skipping..."
fi

echo "==> Running Are The Types Wrong?"
if [ -f "./node_modules/.bin/attw" ]; then
  ./node_modules/.bin/attw --pack dist -f json >.attw.json || true
  node scripts/utils/attw-report.cjs
else
  echo "ATTW not found, skipping..."
fi

echo "==> Running publint"
if [ -f "./node_modules/.bin/publint" ]; then
  ./node_modules/.bin/publint dist
else
  echo "Publint not found, skipping..."
fi
