#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running pre-commit checks..."
echo "Running linter..."
bun run lint || exit 1
echo "Running type check..."
bun run typecheck || exit 1
echo "Pre-commit checks passed!"
