name = "neocode-console"
main = "./.output/server/index.mjs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "neocode-console-prod"
routes = [
  { pattern = "neo.khulnasoft.com/*", zone_name = "khulnasoft.com" }
]

[env.dev]
name = "neocode-console-dev"
routes = [
  { pattern = "dev.neo.khulnasoft.com/*", zone_name = "khulnasoft.com" }
]

[env.staging]
name = "neocode-console-staging"
routes = [
  { pattern = "staging.neo.khulnasoft.com/*", zone_name = "khulnasoft.com" }
]

[[env.production.kv_namespaces]]
binding = "SESSIONS"
id = "d20ff02478d64d99848e7100af98f52f"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "bd44a1cb139a478b9045b0ccad16e40e"

[[env.dev.kv_namespaces]]
binding = "SESSIONS"
id = "d20ff02478d64d99848e7100af98f52f"

[[env.dev.kv_namespaces]]
binding = "CACHE"
id = "bd44a1cb139a478b9045b0ccad16e40e"
