name: neocode

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  neocode:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /neocode') ||
      startsWith(github.event.comment.body, '/neocode')
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run neocode
        uses: neopilot-ai/neocode/github@latest
        env:
          NEOCODE_API_KEY: ${{ secrets.NEOCODE_API_KEY }}
          NEOCODE_PERMISSION: '{"bash": "deny"}'
        with:
          model: neocode/claude-opus-4-5
